const meal = ({
  id,
  name,
  slots,
  calories,
  protein,
  carbs,
  fat,
  portionItems,
  ingredients,
  primaryIngredients,
  tags = [],
  goalTags = [],
  description,
  recipe,
  substitutions = [],
}) => ({
  id,
  name,
  slots: Array.isArray(slots) ? slots : [slots],
  calories,
  protein,
  carbs,
  fat,
  portionItems,
  ingredients,
  primaryIngredients,
  tags,
  goalTags,
  description,
  recipe,
  substitutions,
});

export const mealDatabase = [
  meal({
    id: 'breakfast-plain-idli-sambar',
    name: 'Plain Idli with Sambar',
    slots: 'breakfast',
    calories: 220,
    protein: 9,
    carbs: 38,
    fat: 3,
    portionItems: [{ label: 'idli', quantity: 2, unit: 'piece' }, { label: 'sambar', quantity: 1, unit: 'cup' }],
    ingredients: ['rice', 'urad dal', 'toor dal', 'tomato', 'onion', 'curry leaves'],
    primaryIngredients: ['rice', 'urad dal'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance', 'fitness'],
    description: 'Steamed fermented rice-lentil cakes with light sambar.',
    recipe: {
      cookTime: '35 min active + fermentation',
      steps: ['Steam fermented idli batter.', 'Cook sambar with dal and vegetables.', 'Serve hot with sambar.'],
      tips: 'Use more sambar and less chutney for a lighter plate.',
    },
  }),
  meal({
    id: 'breakfast-vegetable-poha',
    name: 'Vegetable Poha',
    slots: 'breakfast',
    calories: 220,
    protein: 6,
    carbs: 36,
    fat: 6,
    portionItems: [{ label: 'poha', quantity: 1, unit: 'bowl' }],
    ingredients: ['poha', 'onion', 'peas', 'carrot', 'mustard seeds', 'turmeric', 'lemon'],
    primaryIngredients: ['poha'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Flattened rice tossed with peas, onion, turmeric, and lemon.',
    recipe: {
      cookTime: '20 min',
      steps: ['Rinse poha briefly.', 'Saute onion and vegetables with mustard and turmeric.', 'Fold in poha and finish with lemon.'],
      tips: 'Add peanuts only if fat allowance permits.',
    },
  }),
  meal({
    id: 'breakfast-besan-chilla',
    name: 'Besan Chilla',
    slots: 'breakfast',
    calories: 210,
    protein: 11,
    carbs: 22,
    fat: 8,
    portionItems: [{ label: 'chilla', quantity: 2, unit: 'piece' }],
    ingredients: ['besan', 'onion', 'tomato', 'green chili', 'curd'],
    primaryIngredients: ['besan'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain', 'maintenance'],
    description: 'Savory chickpea flour pancakes with vegetables.',
    recipe: {
      cookTime: '15 min',
      steps: ['Whisk besan batter with spices.', 'Add onion and tomato.', 'Cook thin pancakes on a tawa.'],
      tips: 'Pair with curd or mint chutney for more protein.',
    },
  }),
  meal({
    id: 'breakfast-moong-dal-chilla',
    name: 'Moong Dal Chilla with Mint Chutney',
    slots: 'breakfast',
    calories: 210,
    protein: 13,
    carbs: 24,
    fat: 6,
    portionItems: [{ label: 'chilla', quantity: 2, unit: 'piece' }],
    ingredients: ['moong dal', 'onion', 'green chili', 'mint'],
    primaryIngredients: ['moong dal'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain', 'fitness'],
    description: 'Protein-forward pancakes made from soaked moong dal.',
    recipe: {
      cookTime: '25 min',
      steps: ['Soak and blend moong dal.', 'Season with chili and cumin.', 'Cook on a tawa and serve with mint chutney.'],
      tips: 'Stuff with paneer if targeting a higher-protein breakfast.',
    },
  }),
  meal({
    id: 'breakfast-oats-porridge',
    name: 'Oats Porridge with Banana and Nuts',
    slots: 'breakfast',
    calories: 280,
    protein: 10,
    carbs: 38,
    fat: 9,
    portionItems: [{ label: 'porridge', quantity: 1, unit: 'bowl' }],
    ingredients: ['oats', 'milk', 'banana', 'almonds', 'chia seeds'],
    primaryIngredients: ['oats', 'milk'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness', 'muscle-gain'],
    description: 'Comforting oats bowl with fruit and healthy fats.',
    recipe: {
      cookTime: '12 min',
      steps: ['Cook oats in milk or water.', 'Top with sliced banana and nuts.', 'Finish with seeds.'],
      tips: 'Use whey in the bowl after cooling slightly for higher protein.',
    },
  }),
  meal({
    id: 'breakfast-sprouts-chaat',
    name: 'Sprouts Chaat',
    slots: 'breakfast',
    calories: 160,
    protein: 11,
    carbs: 22,
    fat: 3,
    portionItems: [{ label: 'sprouts chaat', quantity: 1, unit: 'bowl' }],
    ingredients: ['sprouts', 'onion', 'tomato', 'lemon', 'coriander leaves'],
    primaryIngredients: ['sprouts'],
    tags: ['pan-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Light but filling sprouts bowl with lemon and vegetables.',
    recipe: {
      cookTime: '10 min',
      steps: ['Boil or steam sprouts.', 'Mix with onion, tomato, and lemon.', 'Finish with coriander and chaat masala.'],
      tips: 'Add curd if you want more volume without too many calories.',
    },
  }),
  meal({
    id: 'breakfast-egg-bhurji-toast',
    name: 'Egg Bhurji with Whole Wheat Toast',
    slots: 'breakfast',
    calories: 310,
    protein: 20,
    carbs: 24,
    fat: 14,
    portionItems: [{ label: 'eggs', quantity: 2, unit: 'piece' }, { label: 'toast', quantity: 2, unit: 'slice' }],
    ingredients: ['eggs', 'onion', 'tomato', 'green chili', 'atta'],
    primaryIngredients: ['eggs'],
    tags: ['north-indian', 'egg', 'high-protein'],
    goalTags: ['muscle-gain', 'fitness', 'weight-loss'],
    description: 'Spiced scrambled eggs with toast.',
    recipe: {
      cookTime: '12 min',
      steps: ['Saute onion, tomato, and chili.', 'Scramble eggs into the masala.', 'Serve with toasted bread or roti.'],
      tips: 'Upgrade to 3 eggs or add egg whites for a muscle-gain version.',
    },
  }),
  meal({
    id: 'breakfast-egg-omelette',
    name: 'Masala Omelette',
    slots: 'breakfast',
    calories: 200,
    protein: 14,
    carbs: 5,
    fat: 14,
    portionItems: [{ label: 'omelette', quantity: 1, unit: 'piece' }],
    ingredients: ['eggs', 'onion', 'tomato', 'green chili'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'A compact high-protein egg breakfast.',
    recipe: {
      cookTime: '10 min',
      steps: ['Whisk eggs with vegetables and spices.', 'Cook on a nonstick pan.', 'Serve folded hot.'],
      tips: 'Add egg whites to boost protein without raising fats much.',
    },
  }),
  meal({
    id: 'breakfast-paneer-bhurji-roti',
    name: 'Paneer Bhurji with Roti',
    slots: 'breakfast',
    calories: 320,
    protein: 19,
    carbs: 20,
    fat: 17,
    portionItems: [{ label: 'paneer bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 1, unit: 'piece' }],
    ingredients: ['paneer', 'onion', 'tomato', 'capsicum', 'atta'],
    primaryIngredients: ['paneer'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Scrambled paneer with one roti for a filling start.',
    recipe: {
      cookTime: '15 min',
      steps: ['Crumble paneer.', 'Cook with onion, tomato, and spices.', 'Serve with a fresh roti.'],
      tips: 'Skip the roti for a leaner, lower-carb breakfast.',
    },
  }),
  meal({
    id: 'breakfast-dalia-upma',
    name: 'Dalia Upma',
    slots: 'breakfast',
    calories: 210,
    protein: 7,
    carbs: 35,
    fat: 4,
    portionItems: [{ label: 'dalia upma', quantity: 1, unit: 'bowl' }],
    ingredients: ['dalia', 'onion', 'peas', 'carrot', 'curry leaves'],
    primaryIngredients: ['dalia'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Broken wheat cooked savory-style with vegetables.',
    recipe: {
      cookTime: '20 min',
      steps: ['Roast dalia.', 'Cook with vegetables and spices.', 'Steam until soft and fluffy.'],
      tips: 'Add moong dal if you need more protein.',
    },
  }),
  meal({
    id: 'breakfast-plain-dosa-coconut',
    name: 'Plain Dosa with Coconut Chutney',
    slots: 'breakfast',
    calories: 170,
    protein: 5,
    carbs: 26,
    fat: 5,
    portionItems: [{ label: 'dosa', quantity: 1, unit: 'piece' }, { label: 'coconut chutney', quantity: 2, unit: 'tbsp' }],
    ingredients: ['rice', 'urad dal', 'coconut'],
    primaryIngredients: ['rice', 'urad dal'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Classic fermented dosa with a small side of coconut chutney.',
    recipe: { cookTime: '20 min + batter prep', steps: ['Spread dosa batter thin on a hot tawa.', 'Cook until crisp.', 'Serve with coconut chutney.'], tips: 'Pair with sambar if you want more protein and fiber.' },
  }),
  meal({
    id: 'breakfast-rava-dosa',
    name: 'Rava Dosa',
    slots: 'breakfast',
    calories: 160,
    protein: 4,
    carbs: 24,
    fat: 5,
    portionItems: [{ label: 'rava dosa', quantity: 1, unit: 'piece' }],
    ingredients: ['rava', 'curd', 'curry leaves'],
    primaryIngredients: ['rava'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance'],
    description: 'Crispy semolina dosa that cooks faster than fermented dosa.',
    recipe: { cookTime: '15 min', steps: ['Make a thin rava batter.', 'Pour loosely on a hot tawa.', 'Cook crisp on both sides.'], tips: 'Keep oil light to retain the breakfast calorie target.' },
  }),
  meal({
    id: 'breakfast-oats-idli',
    name: 'Oats Idli',
    slots: 'breakfast',
    calories: 180,
    protein: 7,
    carbs: 29,
    fat: 4,
    portionItems: [{ label: 'idli', quantity: 2, unit: 'piece' }],
    ingredients: ['oats', 'rava', 'curd'],
    primaryIngredients: ['oats', 'rava'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Lighter idli variation made with oats and semolina.',
    recipe: { cookTime: '20 min', steps: ['Roast and pulse oats.', 'Mix with rava and curd.', 'Steam in idli moulds.'], tips: 'Serve with sambar to improve satiety.' },
  }),
  meal({
    id: 'breakfast-veg-uttapam',
    name: 'Vegetable Uttapam',
    slots: 'breakfast',
    calories: 190,
    protein: 6,
    carbs: 28,
    fat: 6,
    portionItems: [{ label: 'uttapam', quantity: 1, unit: 'piece' }],
    ingredients: ['rice', 'urad dal', 'onion', 'tomato', 'green chili'],
    primaryIngredients: ['rice', 'urad dal'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Thicker rice-lentil pancake loaded with vegetables.',
    recipe: { cookTime: '18 min', steps: ['Pour batter thicker than dosa.', 'Top with chopped vegetables.', 'Cook covered and flip once.'], tips: 'A good savory breakfast when you want more chew and volume.' },
  }),
  meal({
    id: 'breakfast-rava-upma',
    name: 'Rava Upma',
    slots: 'breakfast',
    calories: 220,
    protein: 6,
    carbs: 34,
    fat: 7,
    portionItems: [{ label: 'upma', quantity: 1, unit: 'bowl' }],
    ingredients: ['rava', 'onion', 'peas', 'carrot', 'curry leaves'],
    primaryIngredients: ['rava'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Semolina breakfast bowl with vegetables and mustard tempering.',
    recipe: { cookTime: '18 min', steps: ['Roast rava lightly.', 'Cook vegetables with tempering.', 'Fold in rava with hot water.'], tips: 'Works well with curd on the side.' },
  }),
  meal({
    id: 'breakfast-oats-upma',
    name: 'Oats Upma',
    slots: 'breakfast',
    calories: 200,
    protein: 8,
    carbs: 29,
    fat: 6,
    portionItems: [{ label: 'oats upma', quantity: 1, unit: 'bowl' }],
    ingredients: ['oats', 'onion', 'peas', 'carrot', 'curry leaves'],
    primaryIngredients: ['oats'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Savory oats with upma-style tempering and vegetables.',
    recipe: { cookTime: '15 min', steps: ['Dry roast oats.', 'Prepare vegetable tempering.', 'Cook oats briefly until fluffy.'], tips: 'A cleaner alternative when you want lower calories than rava upma.' },
  }),
  meal({
    id: 'breakfast-pesarattu',
    name: 'Pesarattu',
    slots: 'breakfast',
    calories: 200,
    protein: 11,
    carbs: 24,
    fat: 6,
    portionItems: [{ label: 'pesarattu', quantity: 2, unit: 'piece' }],
    ingredients: ['moong dal', 'green chili', 'ginger'],
    primaryIngredients: ['moong dal'],
    tags: ['south-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain', 'fitness'],
    description: 'Andhra-style moong dal dosa with solid protein density.',
    recipe: { cookTime: '20 min', steps: ['Soak and blend moong dal batter.', 'Season lightly.', 'Cook as thin crepes.'], tips: 'Great breakfast for lean-muscle days.' },
  }),
  meal({
    id: 'breakfast-pongal',
    name: 'Ven Pongal',
    slots: 'breakfast',
    calories: 250,
    protein: 8,
    carbs: 36,
    fat: 8,
    portionItems: [{ label: 'pongal', quantity: 1, unit: 'bowl' }],
    ingredients: ['rice', 'moong dal', 'ghee', 'pepper', 'cumin'],
    primaryIngredients: ['rice', 'moong dal'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance'],
    description: 'Soft rice-moong breakfast seasoned with pepper and cumin.',
    recipe: { cookTime: '25 min', steps: ['Cook rice and moong dal until soft.', 'Add pepper-cumin tempering.', 'Finish with a small amount of ghee.'], tips: 'Keep ghee modest if calories are tighter.' },
  }),
  meal({
    id: 'breakfast-aloo-paratha-curd',
    name: 'Aloo Paratha with Curd',
    slots: 'breakfast',
    calories: 350,
    protein: 10,
    carbs: 48,
    fat: 12,
    portionItems: [{ label: 'aloo paratha', quantity: 1, unit: 'piece' }, { label: 'curd', quantity: 0.5, unit: 'cup' }],
    ingredients: ['atta', 'potato', 'curd'],
    primaryIngredients: ['atta', 'potato'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Classic stuffed paratha breakfast with curd.',
    recipe: { cookTime: '25 min', steps: ['Prepare spiced potato filling.', 'Stuff and roll paratha.', 'Cook on tawa and serve with curd.'], tips: 'Best used on higher-calorie days, not as the default cutting breakfast.' },
  }),
  meal({
    id: 'breakfast-paneer-paratha-curd',
    name: 'Paneer Paratha with Curd',
    slots: 'breakfast',
    calories: 320,
    protein: 16,
    carbs: 34,
    fat: 13,
    portionItems: [{ label: 'paneer paratha', quantity: 1, unit: 'piece' }, { label: 'curd', quantity: 0.5, unit: 'cup' }],
    ingredients: ['atta', 'paneer', 'curd'],
    primaryIngredients: ['atta', 'paneer'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Stuffed paneer paratha that works better for protein-focused breakfasts.',
    recipe: { cookTime: '22 min', steps: ['Crumble paneer with spices.', 'Stuff into dough and roll.', 'Cook on tawa and serve with curd.'], tips: 'A stronger option than aloo paratha when protein matters.' },
  }),
  meal({
    id: 'breakfast-methi-paratha',
    name: 'Methi Paratha',
    slots: 'breakfast',
    calories: 220,
    protein: 6,
    carbs: 29,
    fat: 8,
    portionItems: [{ label: 'methi paratha', quantity: 1, unit: 'piece' }],
    ingredients: ['atta', 'methi'],
    primaryIngredients: ['atta', 'methi'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance'],
    description: 'Fenugreek flatbread with earthy flavor and decent satiety.',
    recipe: { cookTime: '18 min', steps: ['Knead atta with chopped methi and spices.', 'Roll into paratha.', 'Cook lightly on a tawa.'], tips: 'Pair with curd or eggs to balance protein.' },
  }),
  meal({
    id: 'breakfast-sabudana-khichdi',
    name: 'Sabudana Khichdi',
    slots: 'breakfast',
    calories: 280,
    protein: 5,
    carbs: 44,
    fat: 9,
    portionItems: [{ label: 'sabudana khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['sabudana', 'peanuts', 'cumin', 'potato'],
    primaryIngredients: ['sabudana'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['fitness', 'maintenance'],
    description: 'Tapioca pearls cooked with cumin and peanuts.',
    recipe: { cookTime: '25 min', steps: ['Soak sabudana properly.', 'Cook with cumin, potato, and peanuts.', 'Finish with lemon.'], tips: 'Better for training days than fat-loss days.' },
  }),
  meal({
    id: 'breakfast-overnight-oats',
    name: 'Overnight Oats',
    slots: 'breakfast',
    calories: 270,
    protein: 13,
    carbs: 34,
    fat: 9,
    portionItems: [{ label: 'overnight oats', quantity: 1, unit: 'bowl' }],
    ingredients: ['oats', 'curd', 'milk', 'banana', 'chia seeds'],
    primaryIngredients: ['oats', 'curd'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness', 'muscle-gain'],
    description: 'Prep-ahead breakfast with oats, curd, fruit, and seeds.',
    recipe: { cookTime: '8 min prep + overnight rest', steps: ['Mix oats, curd, and milk.', 'Add fruit and seeds.', 'Chill overnight.'], tips: 'Very useful for busy mornings.' },
  }),
  meal({
    id: 'breakfast-quinoa-upma',
    name: 'Quinoa Upma',
    slots: 'breakfast',
    calories: 230,
    protein: 9,
    carbs: 31,
    fat: 7,
    portionItems: [{ label: 'quinoa upma', quantity: 1, unit: 'bowl' }],
    ingredients: ['quinoa', 'onion', 'peas', 'carrot', 'curry leaves'],
    primaryIngredients: ['quinoa'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'fitness', 'maintenance'],
    description: 'Higher-protein grain upma using quinoa.',
    recipe: { cookTime: '22 min', steps: ['Rinse quinoa well.', 'Cook with upma-style vegetable tempering.', 'Fluff and serve.'], tips: 'Helpful when you want more protein than standard semolina breakfasts.' },
  }),
  meal({
    id: 'breakfast-dhokla',
    name: 'Dhokla',
    slots: 'breakfast',
    calories: 180,
    protein: 8,
    carbs: 24,
    fat: 5,
    portionItems: [{ label: 'dhokla', quantity: 4, unit: 'piece' }],
    ingredients: ['besan', 'curd'],
    primaryIngredients: ['besan'],
    tags: ['west-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Steamed fermented besan cakes that stay light and portable.',
    recipe: { cookTime: '20 min', steps: ['Prepare dhokla batter.', 'Steam until set.', 'Temper lightly and serve.'], tips: 'A great breakfast when you want something easy to digest.' },
  }),

  meal({
    id: 'snack-whey-shake',
    name: 'Whey Protein Shake',
    slots: ['snack1', 'snack2'],
    calories: 140,
    protein: 24,
    carbs: 4,
    fat: 2,
    portionItems: [{ label: 'whey shake', quantity: 1, unit: 'scoop' }],
    ingredients: ['whey protein', 'milk'],
    primaryIngredients: ['whey protein'],
    tags: ['high-protein'],
    goalTags: ['muscle-gain', 'weight-loss', 'fitness'],
    description: 'Fast and reliable protein snack.',
    recipe: {
      cookTime: '2 min',
      steps: ['Blend whey with water or milk.', 'Shake until smooth.', 'Serve chilled or at room temperature.'],
      tips: 'Use water for lower calories and faster digestion.',
    },
  }),
  meal({
    id: 'snack-curd-flax',
    name: 'Curd with Honey and Flaxseeds',
    slots: ['snack1', 'snack2'],
    calories: 180,
    protein: 9,
    carbs: 18,
    fat: 7,
    portionItems: [{ label: 'curd', quantity: 1, unit: 'cup' }],
    ingredients: ['curd', 'honey', 'flaxseeds'],
    primaryIngredients: ['curd'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Cool, digestible snack with probiotics and fiber.',
    recipe: {
      cookTime: '3 min',
      steps: ['Whisk curd until smooth.', 'Add flaxseeds and a little honey.', 'Serve chilled.'],
      tips: 'Swap honey for fruit if you want less added sugar.',
    },
  }),
  meal({
    id: 'snack-roasted-chana',
    name: 'Roasted Chana',
    slots: ['snack1', 'snack2'],
    calories: 110,
    protein: 6,
    carbs: 17,
    fat: 2,
    portionItems: [{ label: 'roasted chana', quantity: 30, unit: 'g' }],
    ingredients: ['chana'],
    primaryIngredients: ['chana'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Portable high-fiber snack.',
    recipe: {
      cookTime: '0 min',
      steps: ['Measure a small serving into a box.', 'Season if needed.', 'Keep it ready for work or travel.'],
      tips: 'Combine with fruit if you need a more filling snack.',
    },
  }),
  meal({
    id: 'snack-fruit-nuts',
    name: 'Apple with Almonds',
    slots: ['snack1', 'snack2'],
    calories: 170,
    protein: 4,
    carbs: 22,
    fat: 7,
    portionItems: [{ label: 'apple', quantity: 1, unit: 'piece' }, { label: 'almonds', quantity: 10, unit: 'piece' }],
    ingredients: ['apple', 'almonds'],
    primaryIngredients: ['apple'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Simple fruit-and-fat combo to reduce cravings.',
    recipe: {
      cookTime: '2 min',
      steps: ['Wash and slice the apple.', 'Add almonds on the side.', 'Pack into a small snack box.'],
      tips: 'Use walnuts instead of almonds if that is what you have.',
    },
  }),
  meal({
    id: 'snack-fruit-chaat',
    name: 'Fruit Chaat',
    slots: ['snack1', 'snack2'],
    calories: 150,
    protein: 2,
    carbs: 34,
    fat: 1,
    portionItems: [{ label: 'fruit chaat', quantity: 1, unit: 'bowl' }],
    ingredients: ['banana', 'apple', 'orange', 'pomegranate', 'lemon'],
    primaryIngredients: ['banana'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Hydrating fruit bowl with chaat masala and lemon.',
    recipe: {
      cookTime: '8 min',
      steps: ['Chop available fruits.', 'Add lemon and a pinch of chaat masala.', 'Serve fresh.'],
      tips: 'Keep banana smaller when targeting lower calories.',
    },
  }),
  meal({
    id: 'snack-boiled-eggs',
    name: 'Boiled Eggs',
    slots: ['snack1', 'snack2'],
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    portionItems: [{ label: 'eggs', quantity: 2, unit: 'piece' }],
    ingredients: ['eggs'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['muscle-gain', 'weight-loss', 'fitness'],
    description: 'Clean protein option for hunger control.',
    recipe: {
      cookTime: '10 min',
      steps: ['Boil eggs.', 'Peel and season lightly.', 'Serve or pack.'],
      tips: 'Add one more egg white if you need more protein without extra fat.',
    },
  }),
  meal({
    id: 'snack-roasted-makhana',
    name: 'Roasted Makhana',
    slots: ['snack1', 'snack2'],
    calories: 110,
    protein: 4,
    carbs: 16,
    fat: 3,
    portionItems: [{ label: 'makhana', quantity: 30, unit: 'g' }],
    ingredients: ['makhana', 'ghee'],
    primaryIngredients: ['makhana'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Light crunchy evening snack with low mess.',
    recipe: {
      cookTime: '8 min',
      steps: ['Dry roast makhana.', 'Add a tiny amount of ghee and spices.', 'Cool before storing.'],
      tips: 'Use very little fat; makhana absorbs it quickly.',
    },
  }),
  meal({
    id: 'snack-paneer-cubes',
    name: 'Paneer Cubes with Chaat Masala',
    slots: ['snack1', 'snack2'],
    calories: 140,
    protein: 9,
    carbs: 4,
    fat: 10,
    portionItems: [{ label: 'paneer', quantity: 50, unit: 'g' }],
    ingredients: ['paneer', 'lemon'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'weight-loss'],
    description: 'Quick protein snack using paneer cubes.',
    recipe: {
      cookTime: '5 min',
      steps: ['Cube paneer.', 'Sprinkle chaat masala and lemon.', 'Serve chilled or lightly warmed.'],
      tips: 'Grill briefly if you want more texture.',
    },
  }),
  meal({
    id: 'snack-coconut-water',
    name: 'Coconut Water',
    slots: ['snack1', 'snack2'],
    calories: 50,
    protein: 1,
    carbs: 12,
    fat: 0,
    portionItems: [{ label: 'coconut water', quantity: 1, unit: 'glass' }],
    ingredients: ['coconut water'],
    primaryIngredients: ['coconut water'],
    tags: ['hydration'],
    goalTags: ['weight-loss', 'fitness', 'maintenance'],
    description: 'Light hydration snack, especially around hotter days or workouts.',
    recipe: { cookTime: '0 min', steps: ['Serve chilled coconut water.'], tips: 'Pair with protein if you need more satiety.' },
  }),
  meal({
    id: 'snack-besan-chilla-small',
    name: 'Besan Chilla (Small)',
    slots: ['snack1', 'snack2'],
    calories: 100,
    protein: 5,
    carbs: 10,
    fat: 4,
    portionItems: [{ label: 'small chilla', quantity: 1, unit: 'piece' }],
    ingredients: ['besan', 'onion', 'tomato'],
    primaryIngredients: ['besan'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Mini savory pancake for a more filling snack slot.',
    recipe: { cookTime: '10 min', steps: ['Make a light besan batter.', 'Cook one small chilla.', 'Serve hot.'], tips: 'Useful when you want a real savory snack instead of packaged food.' },
  }),
  meal({
    id: 'snack-oat-energy-ball',
    name: 'Oat Energy Balls',
    slots: ['snack1', 'snack2'],
    calories: 180,
    protein: 5,
    carbs: 22,
    fat: 8,
    portionItems: [{ label: 'energy ball', quantity: 2, unit: 'piece' }],
    ingredients: ['oats', 'honey', 'peanuts', 'flaxseeds'],
    primaryIngredients: ['oats'],
    tags: ['vegetarian'],
    goalTags: ['fitness', 'maintenance'],
    description: 'Portable homemade energy snack using oats and seeds.',
    recipe: { cookTime: '12 min', steps: ['Mix oats, seeds, and binder.', 'Roll into balls.', 'Chill until firm.'], tips: 'Keep portions tight because calories add up quickly.' },
  }),
  meal({
    id: 'snack-murmura-chaat',
    name: 'Murmura Chaat',
    slots: ['snack1', 'snack2'],
    calories: 120,
    protein: 3,
    carbs: 22,
    fat: 2,
    portionItems: [{ label: 'murmura chaat', quantity: 1, unit: 'bowl' }],
    ingredients: ['murmura', 'onion', 'tomato', 'lemon'],
    primaryIngredients: ['murmura'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Light puffed-rice chaat that gives snack volume at low calories.',
    recipe: { cookTime: '8 min', steps: ['Mix murmura with chopped vegetables and lemon.', 'Season lightly.', 'Serve immediately.'], tips: 'Best eaten fresh before it softens.' },
  }),
  meal({
    id: 'snack-dhokla-small',
    name: 'Dhokla',
    slots: ['snack1', 'snack2'],
    calories: 130,
    protein: 6,
    carbs: 18,
    fat: 4,
    portionItems: [{ label: 'dhokla', quantity: 3, unit: 'piece' }],
    ingredients: ['besan', 'curd'],
    primaryIngredients: ['besan'],
    tags: ['west-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Steamed snack that works especially well in the evening.',
    recipe: { cookTime: '15 min', steps: ['Steam dhokla batter.', 'Cool and portion into pieces.', 'Serve with chutney if needed.'], tips: 'A much cleaner snack than fried namkeen.' },
  }),
  meal({
    id: 'snack-chana-chaat',
    name: 'Chana Chaat',
    slots: ['snack1', 'snack2'],
    calories: 160,
    protein: 8,
    carbs: 24,
    fat: 3,
    portionItems: [{ label: 'chana chaat', quantity: 1, unit: 'bowl' }],
    ingredients: ['chole', 'onion', 'tomato', 'lemon'],
    primaryIngredients: ['chole'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness', 'maintenance'],
    description: 'Boiled chickpeas with lemon and vegetables for a filling snack.',
    recipe: { cookTime: '10 min', steps: ['Use boiled chana.', 'Mix with onion, tomato, and lemon.', 'Serve chilled or room temperature.'], tips: 'A strong option when you need more fiber and fullness.' },
  }),
  meal({
    id: 'snack-veggie-sandwich',
    name: 'Vegetable Sandwich',
    slots: ['snack1', 'snack2'],
    calories: 220,
    protein: 7,
    carbs: 32,
    fat: 7,
    portionItems: [{ label: 'sandwich', quantity: 1, unit: 'piece' }],
    ingredients: ['atta', 'cucumber', 'tomato', 'capsicum', 'curd'],
    primaryIngredients: ['atta'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Whole-grain style vegetable sandwich for a more substantial snack.',
    recipe: { cookTime: '10 min', steps: ['Assemble vegetables between bread.', 'Add light spread or curd-based layer.', 'Toast if desired.'], tips: 'Better suited to active days than tighter fat-loss days.' },
  }),
  meal({
    id: 'snack-boiled-corn',
    name: 'Boiled Corn with Lime and Chili',
    slots: ['snack1', 'snack2'],
    calories: 130,
    protein: 4,
    carbs: 26,
    fat: 2,
    portionItems: [{ label: 'corn', quantity: 1, unit: 'ear' }],
    ingredients: ['corn', 'lemon'],
    primaryIngredients: ['corn'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Classic street-style corn done in a simpler, lighter format.',
    recipe: { cookTime: '12 min', steps: ['Boil or steam corn.', 'Add lime, chili, and salt.', 'Serve hot.'], tips: 'Good for satiety but still a carb-led snack.' },
  }),
  meal({
    id: 'snack-lassi',
    name: 'Low-Fat Lassi',
    slots: ['snack1', 'snack2'],
    calories: 130,
    protein: 7,
    carbs: 16,
    fat: 3,
    portionItems: [{ label: 'lassi', quantity: 1, unit: 'glass' }],
    ingredients: ['curd'],
    primaryIngredients: ['curd'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Cooling dairy snack that also supports digestion.',
    recipe: { cookTime: '5 min', steps: ['Blend curd with water.', 'Season lightly or keep plain.', 'Serve chilled.'], tips: 'Avoid adding too much sugar if you are cutting.' },
  }),
  meal({
    id: 'snack-mixed-fruit-bowl',
    name: 'Mixed Fruit Bowl',
    slots: ['snack1', 'snack2'],
    calories: 100,
    protein: 2,
    carbs: 24,
    fat: 1,
    portionItems: [{ label: 'fruit bowl', quantity: 1, unit: 'cup' }],
    ingredients: ['apple', 'banana', 'orange', 'papaya'],
    primaryIngredients: ['apple'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness', 'maintenance'],
    description: 'Simple fruit bowl for lighter snack windows.',
    recipe: { cookTime: '5 min', steps: ['Chop available fruits.', 'Mix in a bowl.', 'Serve fresh.'], tips: 'Better paired with protein if hunger is high.' },
  }),

  meal({
    id: 'lunch-dal-rice',
    name: 'Dal Rice',
    slots: 'lunch',
    calories: 450,
    protein: 16,
    carbs: 68,
    fat: 10,
    portionItems: [{ label: 'dal', quantity: 1, unit: 'cup' }, { label: 'rice', quantity: 1, unit: 'cup' }],
    ingredients: ['toor dal', 'rice', 'tomato', 'onion', 'ghee'],
    primaryIngredients: ['dal', 'rice'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Classic lentil-and-rice comfort meal.',
    recipe: {
      cookTime: '30 min',
      steps: ['Pressure cook dal.', 'Prepare simple tadka.', 'Serve with steamed rice.'],
      tips: 'Pair with salad to improve satiety.',
    },
  }),
  meal({
    id: 'lunch-rajma-chawal',
    name: 'Rajma Chawal',
    slots: 'lunch',
    calories: 480,
    protein: 18,
    carbs: 73,
    fat: 11,
    portionItems: [{ label: 'rajma', quantity: 1, unit: 'cup' }, { label: 'rice', quantity: 1, unit: 'cup' }],
    ingredients: ['rajma', 'rice', 'onion', 'tomato', 'ginger', 'garlic'],
    primaryIngredients: ['rajma', 'rice'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Kidney beans in gravy with rice.',
    recipe: {
      cookTime: '40 min',
      steps: ['Soak and pressure cook rajma.', 'Make onion-tomato masala.', 'Simmer and serve with rice.'],
      tips: 'Works best as a lunch meal rather than dinner.',
    },
  }),
  meal({
    id: 'lunch-chole-roti',
    name: 'Chana Masala with Roti',
    slots: 'lunch',
    calories: 500,
    protein: 18,
    carbs: 70,
    fat: 15,
    portionItems: [{ label: 'chana masala', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 3, unit: 'piece' }],
    ingredients: ['chole', 'atta', 'onion', 'tomato', 'ginger', 'garam masala'],
    primaryIngredients: ['chole', 'atta'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Chickpea curry with rotis.',
    recipe: {
      cookTime: '35 min',
      steps: ['Cook soaked chole.', 'Prepare masala gravy.', 'Simmer and serve with fresh rotis.'],
      tips: 'For leaning out, drop from 3 rotis to 2 and add salad.',
    },
  }),
  meal({
    id: 'lunch-moong-dal-roti-salad',
    name: 'Moong Dal with Roti and Salad',
    slots: 'lunch',
    calories: 400,
    protein: 18,
    carbs: 52,
    fat: 9,
    portionItems: [{ label: 'moong dal', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }, { label: 'salad', quantity: 1, unit: 'bowl' }],
    ingredients: ['moong dal', 'atta', 'cucumber', 'tomato', 'onion'],
    primaryIngredients: ['moong dal', 'atta'],
    tags: ['vegetarian', 'high-fiber'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Balanced, digestion-friendly lunch with salad.',
    recipe: {
      cookTime: '25 min',
      steps: ['Cook moong dal until soft.', 'Season lightly with cumin.', 'Serve with rotis and raw salad.'],
      tips: 'This is a strong default fat-loss lunch.',
    },
  }),
  meal({
    id: 'lunch-palak-paneer-roti',
    name: 'Palak Paneer with Roti',
    slots: 'lunch',
    calories: 480,
    protein: 24,
    carbs: 34,
    fat: 26,
    portionItems: [{ label: 'palak paneer', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['paneer', 'spinach', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['paneer', 'spinach'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Paneer in spinach gravy with rotis.',
    recipe: {
      cookTime: '30 min',
      steps: ['Blanch and blend spinach.', 'Cook masala base.', 'Add paneer and simmer with spinach.'],
      tips: 'Use less cream and more spinach for a leaner version.',
    },
  }),
  meal({
    id: 'lunch-paneer-tikka-bowl',
    name: 'Paneer Tikka Bowl',
    slots: 'lunch',
    calories: 420,
    protein: 25,
    carbs: 28,
    fat: 22,
    portionItems: [{ label: 'paneer tikka bowl', quantity: 1, unit: 'bowl' }],
    ingredients: ['paneer', 'curd', 'capsicum', 'onion', 'quinoa', 'cucumber'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein', 'bowl'],
    goalTags: ['muscle-gain', 'weight-loss', 'fitness'],
    description: 'Grilled paneer with a grain base and salad.',
    recipe: {
      cookTime: '25 min',
      steps: ['Marinate paneer in curd and spices.', 'Grill paneer and vegetables.', 'Assemble over quinoa or salad.'],
      tips: 'Skip the grain base for a lower-carb day.',
    },
  }),
  meal({
    id: 'lunch-egg-curry-roti',
    name: 'Egg Curry with Roti',
    slots: 'lunch',
    calories: 460,
    protein: 22,
    carbs: 34,
    fat: 24,
    portionItems: [{ label: 'egg curry', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['eggs', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Boiled eggs in onion-tomato gravy with roti.',
    recipe: {
      cookTime: '25 min',
      steps: ['Boil eggs.', 'Make onion-tomato masala.', 'Simmer eggs in gravy and serve with rotis.'],
      tips: 'Use 3 eggs if you want to push protein up without too many carbs.',
    },
  }),
  meal({
    id: 'lunch-tofu-bhurji-roti',
    name: 'Tofu Bhurji with Roti',
    slots: 'lunch',
    calories: 380,
    protein: 24,
    carbs: 28,
    fat: 16,
    portionItems: [{ label: 'tofu bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['tofu', 'onion', 'tomato', 'capsicum', 'atta'],
    primaryIngredients: ['tofu'],
    tags: ['vegan', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'Scrambled tofu with rotis.',
    recipe: {
      cookTime: '18 min',
      steps: ['Crumble tofu.', 'Cook with onion, tomato, and capsicum.', 'Serve with rotis.'],
      tips: 'Great paneer substitute for dairy-free users.',
    },
  }),
  meal({
    id: 'lunch-khichdi',
    name: 'Khichdi',
    slots: 'lunch',
    calories: 300,
    protein: 11,
    carbs: 48,
    fat: 7,
    portionItems: [{ label: 'khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['rice', 'moong dal', 'ghee', 'turmeric', 'peas'],
    primaryIngredients: ['rice', 'moong dal'],
    tags: ['vegetarian', 'comfort'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Rice and lentils cooked together for an easy lunch.',
    recipe: {
      cookTime: '25 min',
      steps: ['Cook rice and dal together.', 'Add vegetables if available.', 'Finish with cumin and minimal ghee.'],
      tips: 'Pair with curd to make it more filling.',
    },
  }),
  meal({
    id: 'lunch-dalia-sabzi-curd',
    name: 'Dalia Bowl with Sabzi and Curd',
    slots: 'lunch',
    calories: 390,
    protein: 14,
    carbs: 55,
    fat: 10,
    portionItems: [{ label: 'dalia', quantity: 1, unit: 'bowl' }, { label: 'sabzi', quantity: 1, unit: 'cup' }, { label: 'curd', quantity: 0.5, unit: 'cup' }],
    ingredients: ['dalia', 'curd', 'carrot', 'peas', 'capsicum'],
    primaryIngredients: ['dalia'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Steady-energy lunch using broken wheat and curd.',
    recipe: {
      cookTime: '22 min',
      steps: ['Cook dalia until fluffy.', 'Prepare a dry sabzi.', 'Serve with curd on the side.'],
      tips: 'Useful when you want rice-like comfort but more fiber.',
    },
  }),
  meal({
    id: 'lunch-kadhi-chawal',
    name: 'Kadhi Chawal',
    slots: 'lunch',
    calories: 420,
    protein: 14,
    carbs: 52,
    fat: 15,
    portionItems: [{ label: 'kadhi', quantity: 1, unit: 'bowl' }, { label: 'rice', quantity: 1, unit: 'cup' }],
    ingredients: ['curd', 'besan', 'rice'],
    primaryIngredients: ['curd', 'besan', 'rice'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance'],
    description: 'Comforting yogurt-besan curry served with rice.',
    recipe: { cookTime: '25 min', steps: ['Cook kadhi slowly until smooth.', 'Steam rice.', 'Serve together hot.'], tips: 'A good rotation dish when you want variety beyond dal.' },
  }),
  meal({
    id: 'lunch-sambar-rice',
    name: 'Sambar Rice',
    slots: 'lunch',
    calories: 380,
    protein: 11,
    carbs: 60,
    fat: 8,
    portionItems: [{ label: 'sambar rice', quantity: 1, unit: 'plate' }],
    ingredients: ['rice', 'toor dal', 'tomato', 'onion', 'curry leaves'],
    primaryIngredients: ['rice', 'toor dal'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Rice folded directly into vegetable sambar for an easy one-plate lunch.',
    recipe: { cookTime: '30 min', steps: ['Prepare sambar.', 'Cook rice separately.', 'Combine or serve together.'], tips: 'A lighter South Indian lunch than biryani-style rice dishes.' },
  }),
  meal({
    id: 'lunch-curd-rice',
    name: 'Curd Rice',
    slots: 'lunch',
    calories: 250,
    protein: 8,
    carbs: 36,
    fat: 7,
    portionItems: [{ label: 'curd rice', quantity: 1, unit: 'cup' }],
    ingredients: ['rice', 'curd', 'curry leaves'],
    primaryIngredients: ['rice', 'curd'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['maintenance'],
    description: 'Cooling curd rice for a light lunch or recovery meal.',
    recipe: { cookTime: '12 min', steps: ['Mix cooked rice with curd.', 'Add simple tempering if desired.', 'Serve chilled or room temperature.'], tips: 'Best when digestion or heat is an issue.' },
  }),
  meal({
    id: 'lunch-vegetable-pulao',
    name: 'Vegetable Pulao',
    slots: 'lunch',
    calories: 320,
    protein: 8,
    carbs: 48,
    fat: 10,
    portionItems: [{ label: 'vegetable pulao', quantity: 1, unit: 'cup' }],
    ingredients: ['rice', 'peas', 'carrot', 'beans', 'onion'],
    primaryIngredients: ['rice'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Rice cooked with mixed vegetables and whole spices.',
    recipe: { cookTime: '25 min', steps: ['Saute whole spices and onion.', 'Add vegetables and rice.', 'Cook until fluffy.'], tips: 'Pair with curd or paneer for a more balanced lunch.' },
  }),
  meal({
    id: 'lunch-brown-rice-dal-sabzi',
    name: 'Brown Rice with Dal and Sabzi',
    slots: 'lunch',
    calories: 500,
    protein: 18,
    carbs: 74,
    fat: 12,
    portionItems: [{ label: 'brown rice', quantity: 1, unit: 'cup' }, { label: 'dal', quantity: 1, unit: 'cup' }, { label: 'sabzi', quantity: 1, unit: 'cup' }],
    ingredients: ['brown rice', 'dal', 'carrot', 'beans', 'tomato'],
    primaryIngredients: ['brown rice', 'dal'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Balanced grain-legume-vegetable lunch with slower digestion.',
    recipe: { cookTime: '35 min', steps: ['Cook brown rice.', 'Prepare dal and sabzi separately.', 'Serve as a complete plate.'], tips: 'A nice steady-energy office lunch.' },
  }),
  meal({
    id: 'lunch-quinoa-khichdi',
    name: 'Quinoa Khichdi',
    slots: 'lunch',
    calories: 320,
    protein: 13,
    carbs: 42,
    fat: 9,
    portionItems: [{ label: 'quinoa khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['quinoa', 'moong dal', 'peas', 'carrot'],
    primaryIngredients: ['quinoa', 'moong dal'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'fitness', 'maintenance'],
    description: 'Higher-protein khichdi swap using quinoa.',
    recipe: { cookTime: '22 min', steps: ['Rinse quinoa and dal.', 'Cook together with vegetables.', 'Season lightly.'], tips: 'A useful swap when you want less rice and more protein density.' },
  }),
  meal({
    id: 'lunch-dal-tadka-roti',
    name: 'Dal Tadka with Roti',
    slots: 'lunch',
    calories: 480,
    protein: 17,
    carbs: 61,
    fat: 13,
    portionItems: [{ label: 'dal tadka', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 3, unit: 'piece' }],
    ingredients: ['dal', 'atta', 'onion', 'tomato', 'garlic'],
    primaryIngredients: ['dal', 'atta'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Tempered dal with rotis as a classic North Indian lunch.',
    recipe: { cookTime: '28 min', steps: ['Cook dal until soft.', 'Prepare garlic-onion tadka.', 'Serve with rotis.'], tips: 'For cutting, use 2 rotis and bigger salad volume.' },
  }),
  meal({
    id: 'lunch-mixed-veg-curry-roti',
    name: 'Mixed Vegetable Curry with Roti',
    slots: 'lunch',
    calories: 430,
    protein: 12,
    carbs: 56,
    fat: 15,
    portionItems: [{ label: 'mixed vegetable curry', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 3, unit: 'piece' }],
    ingredients: ['atta', 'peas', 'carrot', 'capsicum', 'tomato', 'onion'],
    primaryIngredients: ['atta'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance'],
    description: 'Seasonal vegetable curry with rotis.',
    recipe: { cookTime: '25 min', steps: ['Cook onion-tomato masala.', 'Add vegetables and simmer.', 'Serve with rotis.'], tips: 'Pair with curd if you need more protein.' },
  }),
  meal({
    id: 'lunch-lauki-chana-dal-roti',
    name: 'Lauki Chana Dal with Roti',
    slots: 'lunch',
    calories: 400,
    protein: 16,
    carbs: 49,
    fat: 10,
    portionItems: [{ label: 'lauki chana dal', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['lauki', 'chana dal', 'atta'],
    primaryIngredients: ['lauki', 'chana dal'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Bottle gourd and chana dal curry with rotis.',
    recipe: { cookTime: '25 min', steps: ['Cook chana dal with lauki.', 'Season with cumin and tomato.', 'Serve with rotis.'], tips: 'Underrated fat-loss lunch because it is filling without being heavy.' },
  }),
  meal({
    id: 'lunch-mushroom-matar-roti',
    name: 'Mushroom Matar with Roti',
    slots: 'lunch',
    calories: 420,
    protein: 15,
    carbs: 44,
    fat: 15,
    portionItems: [{ label: 'mushroom matar', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['mushroom', 'peas', 'atta', 'onion', 'tomato'],
    primaryIngredients: ['mushroom', 'peas'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Mushroom and peas curry with rotis.',
    recipe: { cookTime: '20 min', steps: ['Cook onion-tomato masala.', 'Add mushrooms and peas.', 'Simmer and serve with rotis.'], tips: 'A nice lunch break from dal-heavy rotations.' },
  }),
  meal({
    id: 'lunch-sprout-salad-bowl',
    name: 'Sprouts and Vegetable Salad Bowl',
    slots: 'lunch',
    calories: 250,
    protein: 14,
    carbs: 28,
    fat: 8,
    portionItems: [{ label: 'sprout salad bowl', quantity: 1, unit: 'large bowl' }],
    ingredients: ['sprouts', 'cucumber', 'tomato', 'onion', 'lemon'],
    primaryIngredients: ['sprouts'],
    tags: ['bowl', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Large sprout bowl for lighter lunches or recomposition phases.',
    recipe: { cookTime: '12 min', steps: ['Steam sprouts if needed.', 'Mix with vegetables and lemon.', 'Serve chilled or room temperature.'], tips: 'Add paneer or eggs if you want a more complete lunch.' },
  }),
  meal({
    id: 'lunch-millet-khichdi',
    name: 'Millet Khichdi',
    slots: 'lunch',
    calories: 320,
    protein: 11,
    carbs: 46,
    fat: 8,
    portionItems: [{ label: 'millet khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['millet', 'moong dal', 'peas', 'carrot'],
    primaryIngredients: ['millet', 'moong dal'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'fitness', 'maintenance'],
    description: 'One-pot millet-and-dal lunch with better fiber than plain rice khichdi.',
    recipe: { cookTime: '25 min', steps: ['Rinse millet and dal.', 'Cook with vegetables and spices.', 'Serve hot.'], tips: 'Good when you want grain diversity.' },
  }),

  meal({
    id: 'dinner-paneer-tikka-salad',
    name: 'Paneer Tikka with Salad',
    slots: 'dinner',
    calories: 350,
    protein: 24,
    carbs: 10,
    fat: 22,
    portionItems: [{ label: 'paneer tikka', quantity: 150, unit: 'g' }, { label: 'salad', quantity: 1, unit: 'bowl' }],
    ingredients: ['paneer', 'curd', 'capsicum', 'onion', 'cucumber'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein', 'light-dinner'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'Lighter dinner centered around grilled paneer.',
    recipe: {
      cookTime: '20 min',
      steps: ['Marinate paneer.', 'Grill with vegetables.', 'Serve with salad and chutney.'],
      tips: 'Skip heavy gravy at dinner if leaning out.',
    },
  }),
  meal({
    id: 'dinner-tofu-stir-fry',
    name: 'Tofu Stir Fry with Vegetables',
    slots: 'dinner',
    calories: 280,
    protein: 20,
    carbs: 14,
    fat: 14,
    portionItems: [{ label: 'tofu stir fry', quantity: 1, unit: 'bowl' }],
    ingredients: ['tofu', 'capsicum', 'broccoli', 'onion', 'garlic'],
    primaryIngredients: ['tofu'],
    tags: ['vegan', 'high-protein', 'light-dinner'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Quick stir fry with tofu and vegetables.',
    recipe: {
      cookTime: '15 min',
      steps: ['Cube tofu.', 'Stir fry garlic and vegetables.', 'Add tofu and cook until lightly crisp.'],
      tips: 'Use minimal oil and a hot pan for better texture.',
    },
  }),
  meal({
    id: 'dinner-moong-dal-khichdi',
    name: 'Moong Dal Khichdi',
    slots: 'dinner',
    calories: 300,
    protein: 12,
    carbs: 46,
    fat: 7,
    portionItems: [{ label: 'khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['rice', 'moong dal', 'cumin', 'ghee'],
    primaryIngredients: ['rice', 'moong dal'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Comforting light dinner for easy digestion.',
    recipe: {
      cookTime: '20 min',
      steps: ['Cook rice and dal with extra water.', 'Season lightly with cumin.', 'Serve soft and warm.'],
      tips: 'Good option on low-appetite or late evenings.',
    },
  }),
  meal({
    id: 'dinner-palak-dal-roti',
    name: 'Palak Dal with Roti',
    slots: 'dinner',
    calories: 400,
    protein: 18,
    carbs: 45,
    fat: 11,
    portionItems: [{ label: 'palak dal', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['spinach', 'dal', 'atta', 'garlic'],
    primaryIngredients: ['spinach', 'dal', 'atta'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance', 'fitness'],
    description: 'Spinach-lentil dinner with rotis.',
    recipe: {
      cookTime: '25 min',
      steps: ['Cook dal.', 'Blend or chop spinach.', 'Combine and temper with garlic.'],
      tips: 'Drop to 1 roti for a lighter dinner.',
    },
  }),
  meal({
    id: 'dinner-egg-bhurji-roti',
    name: 'Egg Bhurji with Rotis',
    slots: 'dinner',
    calories: 380,
    protein: 22,
    carbs: 28,
    fat: 18,
    portionItems: [{ label: 'egg bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['eggs', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance', 'fitness'],
    description: 'Simple egg dinner with controlled carbs.',
    recipe: {
      cookTime: '15 min',
      steps: ['Prepare masala base.', 'Scramble eggs into it.', 'Serve with fresh rotis.'],
      tips: 'Use 2 whole eggs plus 2 whites for a leaner high-protein dinner.',
    },
  }),
  meal({
    id: 'dinner-paneer-bhurji-roti',
    name: 'Paneer Bhurji with Rotis',
    slots: 'dinner',
    calories: 380,
    protein: 21,
    carbs: 26,
    fat: 19,
    portionItems: [{ label: 'paneer bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['paneer', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Reliable vegetarian dinner with good protein.',
    recipe: {
      cookTime: '18 min',
      steps: ['Crumble paneer.', 'Cook with masala.', 'Serve with rotis.'],
      tips: 'Works well with cucumber salad on the side.',
    },
  }),
  meal({
    id: 'dinner-dalia-khichdi',
    name: 'Dalia Khichdi',
    slots: 'dinner',
    calories: 280,
    protein: 9,
    carbs: 44,
    fat: 7,
    portionItems: [{ label: 'dalia khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['dalia', 'carrot', 'peas', 'onion'],
    primaryIngredients: ['dalia'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Broken wheat one-pot dinner with vegetables.',
    recipe: {
      cookTime: '22 min',
      steps: ['Roast dalia lightly.', 'Cook with vegetables and spices.', 'Serve soft and hot.'],
      tips: 'Useful when you want a cereal-based dinner lighter than roti-sabzi.',
    },
  }),
  meal({
    id: 'dinner-oats-khichdi',
    name: 'Oats Khichdi with Vegetables',
    slots: 'dinner',
    calories: 260,
    protein: 10,
    carbs: 38,
    fat: 7,
    portionItems: [{ label: 'oats khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['oats', 'moong dal', 'peas', 'carrot'],
    primaryIngredients: ['oats'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Quick oats-based savory bowl.',
    recipe: {
      cookTime: '15 min',
      steps: ['Toast oats lightly.', 'Cook with vegetables and moong dal.', 'Serve warm.'],
      tips: 'Helps on nights when digestion needs to stay easy.',
    },
  }),
  meal({
    id: 'dinner-kadhi-roti',
    name: 'Kadhi with 1 Roti',
    slots: 'dinner',
    calories: 280,
    protein: 10,
    carbs: 30,
    fat: 11,
    portionItems: [{ label: 'kadhi', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 1, unit: 'piece' }],
    ingredients: ['curd', 'besan', 'atta'],
    primaryIngredients: ['curd', 'besan'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Simple lighter dinner with one roti.',
    recipe: {
      cookTime: '20 min',
      steps: ['Whisk curd and besan.', 'Cook slowly until smooth.', 'Serve with one roti.'],
      tips: 'Avoid a very oily tempering if cutting calories.',
    },
  }),
  meal({
    id: 'dinner-vegetable-soup-toast',
    name: 'Vegetable Soup with Multigrain Toast',
    slots: 'dinner',
    calories: 280,
    protein: 8,
    carbs: 34,
    fat: 10,
    portionItems: [{ label: 'vegetable soup', quantity: 1, unit: 'bowl' }, { label: 'toast', quantity: 2, unit: 'slice' }],
    ingredients: ['carrot', 'tomato', 'beans', 'atta'],
    primaryIngredients: ['atta'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Simple light soup dinner with toast.',
    recipe: { cookTime: '20 min', steps: ['Cook and blend vegetables into soup.', 'Season lightly.', 'Serve with toasted bread.'], tips: 'Add paneer cubes if you need more protein.' },
  }),
  meal({
    id: 'dinner-mixed-dal-roti',
    name: 'Mixed Dal with Roti',
    slots: 'dinner',
    calories: 420,
    protein: 19,
    carbs: 48,
    fat: 12,
    portionItems: [{ label: 'mixed dal', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['dal', 'atta', 'onion', 'tomato'],
    primaryIngredients: ['dal', 'atta'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Mixed lentil dinner with moderate carbs.',
    recipe: { cookTime: '28 min', steps: ['Cook mixed dals until soft.', 'Temper lightly.', 'Serve with two rotis.'], tips: 'Reliable dinner when you want more protein than khichdi.' },
  }),
  meal({
    id: 'dinner-sabzi-roti-curd',
    name: 'Sabzi with Rotis and Curd',
    slots: 'dinner',
    calories: 370,
    protein: 13,
    carbs: 41,
    fat: 14,
    portionItems: [{ label: 'sabzi', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }, { label: 'curd', quantity: 0.5, unit: 'cup' }],
    ingredients: ['atta', 'curd', 'carrot', 'beans', 'capsicum'],
    primaryIngredients: ['atta', 'curd'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'weight-loss'],
    description: 'Simple home-style dinner built around dry sabzi and curd.',
    recipe: { cookTime: '22 min', steps: ['Make a dry sabzi.', 'Cook rotis fresh.', 'Serve with plain curd.'], tips: 'A practical default dinner for daily home use.' },
  }),
  meal({
    id: 'dinner-quinoa-salad-bowl',
    name: 'Quinoa Salad Bowl',
    slots: 'dinner',
    calories: 300,
    protein: 10,
    carbs: 36,
    fat: 10,
    portionItems: [{ label: 'quinoa salad', quantity: 1, unit: 'bowl' }],
    ingredients: ['quinoa', 'cucumber', 'tomato', 'lemon'],
    primaryIngredients: ['quinoa'],
    tags: ['bowl', 'vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Clean quinoa bowl with vegetables and lemon dressing.',
    recipe: { cookTime: '18 min', steps: ['Cook quinoa.', 'Cool slightly.', 'Toss with vegetables and lemon.'], tips: 'Add paneer or tofu if protein is falling short.' },
  }),
  meal({
    id: 'dinner-sambar-small-rice',
    name: 'Sambar with Small Rice Portion',
    slots: 'dinner',
    calories: 280,
    protein: 10,
    carbs: 40,
    fat: 6,
    portionItems: [{ label: 'sambar', quantity: 1, unit: 'cup' }, { label: 'rice', quantity: 0.5, unit: 'cup' }],
    ingredients: ['toor dal', 'rice', 'tomato', 'onion', 'curry leaves'],
    primaryIngredients: ['toor dal', 'rice'],
    tags: ['south-indian', 'vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Lighter South Indian dinner with a small rice serving.',
    recipe: { cookTime: '25 min', steps: ['Cook sambar.', 'Steam a small rice portion.', 'Serve together.'], tips: 'Useful if you want comfort without a heavy dinner load.' },
  }),
  meal({
    id: 'dinner-sprouted-moong-egg-salad',
    name: 'Sprouted Moong Salad with Egg',
    slots: 'dinner',
    calories: 230,
    protein: 16,
    carbs: 18,
    fat: 9,
    portionItems: [{ label: 'sprout salad', quantity: 1, unit: 'bowl' }, { label: 'egg', quantity: 1, unit: 'piece' }],
    ingredients: ['sprouts', 'eggs', 'cucumber', 'tomato', 'lemon'],
    primaryIngredients: ['sprouts', 'eggs'],
    tags: ['egg', 'high-protein', 'light-dinner'],
    goalTags: ['weight-loss', 'fitness', 'muscle-gain'],
    description: 'Lean, high-protein dinner bowl with sprouts and boiled egg.',
    recipe: { cookTime: '12 min', steps: ['Prepare sprout salad.', 'Add boiled egg.', 'Season lightly with lemon and pepper.'], tips: 'One of the cleanest dinner options in the planner.' },
  }),
  meal({
    id: 'dinner-stuffed-capsicum-paneer',
    name: 'Stuffed Capsicum with Paneer',
    slots: 'dinner',
    calories: 300,
    protein: 18,
    carbs: 16,
    fat: 17,
    portionItems: [{ label: 'stuffed capsicum', quantity: 2, unit: 'piece' }],
    ingredients: ['capsicum', 'paneer', 'onion', 'tomato'],
    primaryIngredients: ['capsicum', 'paneer'],
    tags: ['vegetarian', 'high-protein', 'light-dinner'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'Paneer-filled capsicums baked or pan-cooked.',
    recipe: { cookTime: '22 min', steps: ['Prepare paneer stuffing.', 'Fill capsicum halves.', 'Bake or covered-cook until tender.'], tips: 'Good variety dinner when rotis start feeling repetitive.' },
  }),
  meal({
    id: 'dinner-makhana-curry-roti',
    name: 'Makhana Curry with Roti',
    slots: 'dinner',
    calories: 320,
    protein: 10,
    carbs: 36,
    fat: 12,
    portionItems: [{ label: 'makhana curry', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 1, unit: 'piece' }],
    ingredients: ['makhana', 'tomato', 'curd', 'atta'],
    primaryIngredients: ['makhana', 'atta'],
    tags: ['vegetarian'],
    goalTags: ['maintenance'],
    description: 'Light tomato-based makhana curry with one roti.',
    recipe: { cookTime: '18 min', steps: ['Roast makhana lightly.', 'Prepare tomato-based gravy.', 'Simmer briefly and serve with roti.'], tips: 'A good dinner when you want something different but still homestyle.' },
  }),
  meal({
    id: 'dinner-palak-paneer-brown-rice',
    name: 'Palak Paneer with Brown Rice (Half Portion)',
    slots: 'dinner',
    calories: 380,
    protein: 22,
    carbs: 30,
    fat: 19,
    portionItems: [{ label: 'palak paneer', quantity: 0.75, unit: 'cup' }, { label: 'brown rice', quantity: 0.5, unit: 'cup' }],
    ingredients: ['paneer', 'spinach', 'brown rice', 'onion', 'tomato'],
    primaryIngredients: ['paneer', 'spinach', 'brown rice'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Smaller rice portion dinner built around palak paneer.',
    recipe: { cookTime: '30 min', steps: ['Make palak paneer.', 'Cook a small portion of brown rice.', 'Serve as a compact dinner plate.'], tips: 'Works well for active evenings when total carbs can stay moderate.' },
  }),
];

export const ingredientAliasMap = {
  atta: ['atta', 'wheat flour', 'whole wheat', 'multigrain toast', 'toast', 'bread'],
  rice: ['rice', 'brown rice', 'steamed rice', 'lemon rice'],
  brown_rice: ['brown rice'],
  quinoa: ['quinoa'],
  millet: ['millet', 'bajra', 'jowar'],
  urad_dal: ['urad dal'],
  toor_dal: ['toor dal', 'arhar dal'],
  moong_dal: ['moong dal', 'green moong'],
  dal: ['dal', 'masoor dal', 'chana dal', 'toor dal', 'moong dal', 'urad dal', 'kaali daal', 'kali dal'],
  rajma: ['rajma'],
  chole: ['chole', 'chana', 'chickpeas', 'chickpea'],
  eggs: ['egg', 'eggs'],
  paneer: ['paneer'],
  tofu: ['tofu'],
  curd: ['curd', 'yogurt', 'dahi', 'greek yogurt'],
  whey_protein: ['whey protein', 'whey'],
  poha: ['poha'],
  besan: ['besan'],
  oats: ['oats'],
  dalia: ['dalia', 'broken wheat'],
  rava: ['rava', 'semolina', 'sooji'],
  methi: ['methi', 'fenugreek leaves'],
  potato: ['potato', 'aloo'],
  sabudana: ['sabudana'],
  sprouts: ['sprouts', 'sprouted moong', 'moong sprouts'],
  makhana: ['makhana', 'fox nuts', 'fox nut'],
  milk: ['milk'],
  spinach: ['spinach', 'palak'],
  lauki: ['lauki', 'bottle gourd'],
  mushroom: ['mushroom', 'mushrooms'],
  corn: ['corn', 'sweet corn'],
  coconut: ['coconut', 'coconut milk', 'coconut water'],
  murmura: ['murmura', 'puffed rice'],
  onion: ['onion'],
  tomato: ['tomato', 'tamatar'],
  capsicum: ['capsicum'],
  peas: ['peas', 'matar'],
  carrot: ['carrot'],
  cucumber: ['cucumber', 'kheera'],
  banana: ['banana'],
  apple: ['apple'],
  orange: ['orange'],
  almonds: ['almond', 'almonds'],
  walnuts: ['walnut', 'walnuts'],
  flaxseeds: ['flaxseeds', 'flax seeds'],
  chia_seeds: ['chia seeds', 'chia'],
};

export const mealDatabaseStats = {
  total: mealDatabase.length,
  breakfast: mealDatabase.filter((item) => item.slots.includes('breakfast')).length,
  lunch: mealDatabase.filter((item) => item.slots.includes('lunch')).length,
  dinner: mealDatabase.filter((item) => item.slots.includes('dinner')).length,
  snacks: mealDatabase.filter((item) => item.slots.includes('snack1') || item.slots.includes('snack2')).length,
};
