const meal = ({
  id,
  name,
  slots,
  calories,
  protein,
  carbs,
  fat,
  portionItems,
  ingredients,
  primaryIngredients,
  tags = [],
  goalTags = [],
  description,
  recipe,
  substitutions = [],
}) => ({
  id,
  name,
  slots: Array.isArray(slots) ? slots : [slots],
  calories,
  protein,
  carbs,
  fat,
  portionItems,
  ingredients,
  primaryIngredients,
  tags,
  goalTags,
  description,
  recipe,
  substitutions,
});

export const mealDatabase = [
  meal({
    id: 'breakfast-plain-idli-sambar',
    name: 'Plain Idli with Sambar',
    slots: 'breakfast',
    calories: 220,
    protein: 9,
    carbs: 38,
    fat: 3,
    portionItems: [{ label: 'idli', quantity: 2, unit: 'piece' }, { label: 'sambar', quantity: 1, unit: 'cup' }],
    ingredients: ['rice', 'urad dal', 'toor dal', 'tomato', 'onion', 'curry leaves'],
    primaryIngredients: ['rice', 'urad dal'],
    tags: ['south-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance', 'fitness'],
    description: 'Steamed fermented rice-lentil cakes with light sambar.',
    recipe: {
      cookTime: '35 min active + fermentation',
      steps: ['Steam fermented idli batter.', 'Cook sambar with dal and vegetables.', 'Serve hot with sambar.'],
      tips: 'Use more sambar and less chutney for a lighter plate.',
    },
  }),
  meal({
    id: 'breakfast-vegetable-poha',
    name: 'Vegetable Poha',
    slots: 'breakfast',
    calories: 220,
    protein: 6,
    carbs: 36,
    fat: 6,
    portionItems: [{ label: 'poha', quantity: 1, unit: 'bowl' }],
    ingredients: ['poha', 'onion', 'peas', 'carrot', 'mustard seeds', 'turmeric', 'lemon'],
    primaryIngredients: ['poha'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Flattened rice tossed with peas, onion, turmeric, and lemon.',
    recipe: {
      cookTime: '20 min',
      steps: ['Rinse poha briefly.', 'Saute onion and vegetables with mustard and turmeric.', 'Fold in poha and finish with lemon.'],
      tips: 'Add peanuts only if fat allowance permits.',
    },
  }),
  meal({
    id: 'breakfast-besan-chilla',
    name: 'Besan Chilla',
    slots: 'breakfast',
    calories: 210,
    protein: 11,
    carbs: 22,
    fat: 8,
    portionItems: [{ label: 'chilla', quantity: 2, unit: 'piece' }],
    ingredients: ['besan', 'onion', 'tomato', 'green chili', 'curd'],
    primaryIngredients: ['besan'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain', 'maintenance'],
    description: 'Savory chickpea flour pancakes with vegetables.',
    recipe: {
      cookTime: '15 min',
      steps: ['Whisk besan batter with spices.', 'Add onion and tomato.', 'Cook thin pancakes on a tawa.'],
      tips: 'Pair with curd or mint chutney for more protein.',
    },
  }),
  meal({
    id: 'breakfast-moong-dal-chilla',
    name: 'Moong Dal Chilla with Mint Chutney',
    slots: 'breakfast',
    calories: 210,
    protein: 13,
    carbs: 24,
    fat: 6,
    portionItems: [{ label: 'chilla', quantity: 2, unit: 'piece' }],
    ingredients: ['moong dal', 'onion', 'green chili', 'mint'],
    primaryIngredients: ['moong dal'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain', 'fitness'],
    description: 'Protein-forward pancakes made from soaked moong dal.',
    recipe: {
      cookTime: '25 min',
      steps: ['Soak and blend moong dal.', 'Season with chili and cumin.', 'Cook on a tawa and serve with mint chutney.'],
      tips: 'Stuff with paneer if targeting a higher-protein breakfast.',
    },
  }),
  meal({
    id: 'breakfast-oats-porridge',
    name: 'Oats Porridge with Banana and Nuts',
    slots: 'breakfast',
    calories: 280,
    protein: 10,
    carbs: 38,
    fat: 9,
    portionItems: [{ label: 'porridge', quantity: 1, unit: 'bowl' }],
    ingredients: ['oats', 'milk', 'banana', 'almonds', 'chia seeds'],
    primaryIngredients: ['oats', 'milk'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness', 'muscle-gain'],
    description: 'Comforting oats bowl with fruit and healthy fats.',
    recipe: {
      cookTime: '12 min',
      steps: ['Cook oats in milk or water.', 'Top with sliced banana and nuts.', 'Finish with seeds.'],
      tips: 'Use whey in the bowl after cooling slightly for higher protein.',
    },
  }),
  meal({
    id: 'breakfast-sprouts-chaat',
    name: 'Sprouts Chaat',
    slots: 'breakfast',
    calories: 160,
    protein: 11,
    carbs: 22,
    fat: 3,
    portionItems: [{ label: 'sprouts chaat', quantity: 1, unit: 'bowl' }],
    ingredients: ['sprouts', 'onion', 'tomato', 'lemon', 'coriander leaves'],
    primaryIngredients: ['sprouts'],
    tags: ['pan-indian', 'vegetarian', 'high-protein'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Light but filling sprouts bowl with lemon and vegetables.',
    recipe: {
      cookTime: '10 min',
      steps: ['Boil or steam sprouts.', 'Mix with onion, tomato, and lemon.', 'Finish with coriander and chaat masala.'],
      tips: 'Add curd if you want more volume without too many calories.',
    },
  }),
  meal({
    id: 'breakfast-egg-bhurji-toast',
    name: 'Egg Bhurji with Whole Wheat Toast',
    slots: 'breakfast',
    calories: 310,
    protein: 20,
    carbs: 24,
    fat: 14,
    portionItems: [{ label: 'eggs', quantity: 2, unit: 'piece' }, { label: 'toast', quantity: 2, unit: 'slice' }],
    ingredients: ['eggs', 'onion', 'tomato', 'green chili', 'atta'],
    primaryIngredients: ['eggs'],
    tags: ['north-indian', 'egg', 'high-protein'],
    goalTags: ['muscle-gain', 'fitness', 'weight-loss'],
    description: 'Spiced scrambled eggs with toast.',
    recipe: {
      cookTime: '12 min',
      steps: ['Saute onion, tomato, and chili.', 'Scramble eggs into the masala.', 'Serve with toasted bread or roti.'],
      tips: 'Upgrade to 3 eggs or add egg whites for a muscle-gain version.',
    },
  }),
  meal({
    id: 'breakfast-egg-omelette',
    name: 'Masala Omelette',
    slots: 'breakfast',
    calories: 200,
    protein: 14,
    carbs: 5,
    fat: 14,
    portionItems: [{ label: 'omelette', quantity: 1, unit: 'piece' }],
    ingredients: ['eggs', 'onion', 'tomato', 'green chili'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'A compact high-protein egg breakfast.',
    recipe: {
      cookTime: '10 min',
      steps: ['Whisk eggs with vegetables and spices.', 'Cook on a nonstick pan.', 'Serve folded hot.'],
      tips: 'Add egg whites to boost protein without raising fats much.',
    },
  }),
  meal({
    id: 'breakfast-paneer-bhurji-roti',
    name: 'Paneer Bhurji with Roti',
    slots: 'breakfast',
    calories: 320,
    protein: 19,
    carbs: 20,
    fat: 17,
    portionItems: [{ label: 'paneer bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 1, unit: 'piece' }],
    ingredients: ['paneer', 'onion', 'tomato', 'capsicum', 'atta'],
    primaryIngredients: ['paneer'],
    tags: ['north-indian', 'vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Scrambled paneer with one roti for a filling start.',
    recipe: {
      cookTime: '15 min',
      steps: ['Crumble paneer.', 'Cook with onion, tomato, and spices.', 'Serve with a fresh roti.'],
      tips: 'Skip the roti for a leaner, lower-carb breakfast.',
    },
  }),
  meal({
    id: 'breakfast-dalia-upma',
    name: 'Dalia Upma',
    slots: 'breakfast',
    calories: 210,
    protein: 7,
    carbs: 35,
    fat: 4,
    portionItems: [{ label: 'dalia upma', quantity: 1, unit: 'bowl' }],
    ingredients: ['dalia', 'onion', 'peas', 'carrot', 'curry leaves'],
    primaryIngredients: ['dalia'],
    tags: ['pan-indian', 'vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Broken wheat cooked savory-style with vegetables.',
    recipe: {
      cookTime: '20 min',
      steps: ['Roast dalia.', 'Cook with vegetables and spices.', 'Steam until soft and fluffy.'],
      tips: 'Add moong dal if you need more protein.',
    },
  }),

  meal({
    id: 'snack-whey-shake',
    name: 'Whey Protein Shake',
    slots: ['snack1', 'snack2'],
    calories: 140,
    protein: 24,
    carbs: 4,
    fat: 2,
    portionItems: [{ label: 'whey shake', quantity: 1, unit: 'scoop' }],
    ingredients: ['whey protein', 'milk'],
    primaryIngredients: ['whey protein'],
    tags: ['high-protein'],
    goalTags: ['muscle-gain', 'weight-loss', 'fitness'],
    description: 'Fast and reliable protein snack.',
    recipe: {
      cookTime: '2 min',
      steps: ['Blend whey with water or milk.', 'Shake until smooth.', 'Serve chilled or at room temperature.'],
      tips: 'Use water for lower calories and faster digestion.',
    },
  }),
  meal({
    id: 'snack-curd-flax',
    name: 'Curd with Honey and Flaxseeds',
    slots: ['snack1', 'snack2'],
    calories: 180,
    protein: 9,
    carbs: 18,
    fat: 7,
    portionItems: [{ label: 'curd', quantity: 1, unit: 'cup' }],
    ingredients: ['curd', 'honey', 'flaxseeds'],
    primaryIngredients: ['curd'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Cool, digestible snack with probiotics and fiber.',
    recipe: {
      cookTime: '3 min',
      steps: ['Whisk curd until smooth.', 'Add flaxseeds and a little honey.', 'Serve chilled.'],
      tips: 'Swap honey for fruit if you want less added sugar.',
    },
  }),
  meal({
    id: 'snack-roasted-chana',
    name: 'Roasted Chana',
    slots: ['snack1', 'snack2'],
    calories: 110,
    protein: 6,
    carbs: 17,
    fat: 2,
    portionItems: [{ label: 'roasted chana', quantity: 30, unit: 'g' }],
    ingredients: ['chana'],
    primaryIngredients: ['chana'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Portable high-fiber snack.',
    recipe: {
      cookTime: '0 min',
      steps: ['Measure a small serving into a box.', 'Season if needed.', 'Keep it ready for work or travel.'],
      tips: 'Combine with fruit if you need a more filling snack.',
    },
  }),
  meal({
    id: 'snack-fruit-nuts',
    name: 'Apple with Almonds',
    slots: ['snack1', 'snack2'],
    calories: 170,
    protein: 4,
    carbs: 22,
    fat: 7,
    portionItems: [{ label: 'apple', quantity: 1, unit: 'piece' }, { label: 'almonds', quantity: 10, unit: 'piece' }],
    ingredients: ['apple', 'almonds'],
    primaryIngredients: ['apple'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Simple fruit-and-fat combo to reduce cravings.',
    recipe: {
      cookTime: '2 min',
      steps: ['Wash and slice the apple.', 'Add almonds on the side.', 'Pack into a small snack box.'],
      tips: 'Use walnuts instead of almonds if that is what you have.',
    },
  }),
  meal({
    id: 'snack-fruit-chaat',
    name: 'Fruit Chaat',
    slots: ['snack1', 'snack2'],
    calories: 150,
    protein: 2,
    carbs: 34,
    fat: 1,
    portionItems: [{ label: 'fruit chaat', quantity: 1, unit: 'bowl' }],
    ingredients: ['banana', 'apple', 'orange', 'pomegranate', 'lemon'],
    primaryIngredients: ['banana'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Hydrating fruit bowl with chaat masala and lemon.',
    recipe: {
      cookTime: '8 min',
      steps: ['Chop available fruits.', 'Add lemon and a pinch of chaat masala.', 'Serve fresh.'],
      tips: 'Keep banana smaller when targeting lower calories.',
    },
  }),
  meal({
    id: 'snack-boiled-eggs',
    name: 'Boiled Eggs',
    slots: ['snack1', 'snack2'],
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    portionItems: [{ label: 'eggs', quantity: 2, unit: 'piece' }],
    ingredients: ['eggs'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['muscle-gain', 'weight-loss', 'fitness'],
    description: 'Clean protein option for hunger control.',
    recipe: {
      cookTime: '10 min',
      steps: ['Boil eggs.', 'Peel and season lightly.', 'Serve or pack.'],
      tips: 'Add one more egg white if you need more protein without extra fat.',
    },
  }),
  meal({
    id: 'snack-roasted-makhana',
    name: 'Roasted Makhana',
    slots: ['snack1', 'snack2'],
    calories: 110,
    protein: 4,
    carbs: 16,
    fat: 3,
    portionItems: [{ label: 'makhana', quantity: 30, unit: 'g' }],
    ingredients: ['makhana', 'ghee'],
    primaryIngredients: ['makhana'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Light crunchy evening snack with low mess.',
    recipe: {
      cookTime: '8 min',
      steps: ['Dry roast makhana.', 'Add a tiny amount of ghee and spices.', 'Cool before storing.'],
      tips: 'Use very little fat; makhana absorbs it quickly.',
    },
  }),
  meal({
    id: 'snack-paneer-cubes',
    name: 'Paneer Cubes with Chaat Masala',
    slots: ['snack1', 'snack2'],
    calories: 140,
    protein: 9,
    carbs: 4,
    fat: 10,
    portionItems: [{ label: 'paneer', quantity: 50, unit: 'g' }],
    ingredients: ['paneer', 'lemon'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'weight-loss'],
    description: 'Quick protein snack using paneer cubes.',
    recipe: {
      cookTime: '5 min',
      steps: ['Cube paneer.', 'Sprinkle chaat masala and lemon.', 'Serve chilled or lightly warmed.'],
      tips: 'Grill briefly if you want more texture.',
    },
  }),

  meal({
    id: 'lunch-dal-rice',
    name: 'Dal Rice',
    slots: 'lunch',
    calories: 450,
    protein: 16,
    carbs: 68,
    fat: 10,
    portionItems: [{ label: 'dal', quantity: 1, unit: 'cup' }, { label: 'rice', quantity: 1, unit: 'cup' }],
    ingredients: ['toor dal', 'rice', 'tomato', 'onion', 'ghee'],
    primaryIngredients: ['dal', 'rice'],
    tags: ['vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Classic lentil-and-rice comfort meal.',
    recipe: {
      cookTime: '30 min',
      steps: ['Pressure cook dal.', 'Prepare simple tadka.', 'Serve with steamed rice.'],
      tips: 'Pair with salad to improve satiety.',
    },
  }),
  meal({
    id: 'lunch-rajma-chawal',
    name: 'Rajma Chawal',
    slots: 'lunch',
    calories: 480,
    protein: 18,
    carbs: 73,
    fat: 11,
    portionItems: [{ label: 'rajma', quantity: 1, unit: 'cup' }, { label: 'rice', quantity: 1, unit: 'cup' }],
    ingredients: ['rajma', 'rice', 'onion', 'tomato', 'ginger', 'garlic'],
    primaryIngredients: ['rajma', 'rice'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Kidney beans in gravy with rice.',
    recipe: {
      cookTime: '40 min',
      steps: ['Soak and pressure cook rajma.', 'Make onion-tomato masala.', 'Simmer and serve with rice.'],
      tips: 'Works best as a lunch meal rather than dinner.',
    },
  }),
  meal({
    id: 'lunch-chole-roti',
    name: 'Chana Masala with Roti',
    slots: 'lunch',
    calories: 500,
    protein: 18,
    carbs: 70,
    fat: 15,
    portionItems: [{ label: 'chana masala', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 3, unit: 'piece' }],
    ingredients: ['chole', 'atta', 'onion', 'tomato', 'ginger', 'garam masala'],
    primaryIngredients: ['chole', 'atta'],
    tags: ['north-indian', 'vegetarian'],
    goalTags: ['maintenance', 'fitness'],
    description: 'Chickpea curry with rotis.',
    recipe: {
      cookTime: '35 min',
      steps: ['Cook soaked chole.', 'Prepare masala gravy.', 'Simmer and serve with fresh rotis.'],
      tips: 'For leaning out, drop from 3 rotis to 2 and add salad.',
    },
  }),
  meal({
    id: 'lunch-moong-dal-roti-salad',
    name: 'Moong Dal with Roti and Salad',
    slots: 'lunch',
    calories: 400,
    protein: 18,
    carbs: 52,
    fat: 9,
    portionItems: [{ label: 'moong dal', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }, { label: 'salad', quantity: 1, unit: 'bowl' }],
    ingredients: ['moong dal', 'atta', 'cucumber', 'tomato', 'onion'],
    primaryIngredients: ['moong dal', 'atta'],
    tags: ['vegetarian', 'high-fiber'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Balanced, digestion-friendly lunch with salad.',
    recipe: {
      cookTime: '25 min',
      steps: ['Cook moong dal until soft.', 'Season lightly with cumin.', 'Serve with rotis and raw salad.'],
      tips: 'This is a strong default fat-loss lunch.',
    },
  }),
  meal({
    id: 'lunch-palak-paneer-roti',
    name: 'Palak Paneer with Roti',
    slots: 'lunch',
    calories: 480,
    protein: 24,
    carbs: 34,
    fat: 26,
    portionItems: [{ label: 'palak paneer', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['paneer', 'spinach', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['paneer', 'spinach'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Paneer in spinach gravy with rotis.',
    recipe: {
      cookTime: '30 min',
      steps: ['Blanch and blend spinach.', 'Cook masala base.', 'Add paneer and simmer with spinach.'],
      tips: 'Use less cream and more spinach for a leaner version.',
    },
  }),
  meal({
    id: 'lunch-paneer-tikka-bowl',
    name: 'Paneer Tikka Bowl',
    slots: 'lunch',
    calories: 420,
    protein: 25,
    carbs: 28,
    fat: 22,
    portionItems: [{ label: 'paneer tikka bowl', quantity: 1, unit: 'bowl' }],
    ingredients: ['paneer', 'curd', 'capsicum', 'onion', 'quinoa', 'cucumber'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein', 'bowl'],
    goalTags: ['muscle-gain', 'weight-loss', 'fitness'],
    description: 'Grilled paneer with a grain base and salad.',
    recipe: {
      cookTime: '25 min',
      steps: ['Marinate paneer in curd and spices.', 'Grill paneer and vegetables.', 'Assemble over quinoa or salad.'],
      tips: 'Skip the grain base for a lower-carb day.',
    },
  }),
  meal({
    id: 'lunch-egg-curry-roti',
    name: 'Egg Curry with Roti',
    slots: 'lunch',
    calories: 460,
    protein: 22,
    carbs: 34,
    fat: 24,
    portionItems: [{ label: 'egg curry', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['eggs', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Boiled eggs in onion-tomato gravy with roti.',
    recipe: {
      cookTime: '25 min',
      steps: ['Boil eggs.', 'Make onion-tomato masala.', 'Simmer eggs in gravy and serve with rotis.'],
      tips: 'Use 3 eggs if you want to push protein up without too many carbs.',
    },
  }),
  meal({
    id: 'lunch-tofu-bhurji-roti',
    name: 'Tofu Bhurji with Roti',
    slots: 'lunch',
    calories: 380,
    protein: 24,
    carbs: 28,
    fat: 16,
    portionItems: [{ label: 'tofu bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['tofu', 'onion', 'tomato', 'capsicum', 'atta'],
    primaryIngredients: ['tofu'],
    tags: ['vegan', 'high-protein'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'Scrambled tofu with rotis.',
    recipe: {
      cookTime: '18 min',
      steps: ['Crumble tofu.', 'Cook with onion, tomato, and capsicum.', 'Serve with rotis.'],
      tips: 'Great paneer substitute for dairy-free users.',
    },
  }),
  meal({
    id: 'lunch-khichdi',
    name: 'Khichdi',
    slots: 'lunch',
    calories: 300,
    protein: 11,
    carbs: 48,
    fat: 7,
    portionItems: [{ label: 'khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['rice', 'moong dal', 'ghee', 'turmeric', 'peas'],
    primaryIngredients: ['rice', 'moong dal'],
    tags: ['vegetarian', 'comfort'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Rice and lentils cooked together for an easy lunch.',
    recipe: {
      cookTime: '25 min',
      steps: ['Cook rice and dal together.', 'Add vegetables if available.', 'Finish with cumin and minimal ghee.'],
      tips: 'Pair with curd to make it more filling.',
    },
  }),
  meal({
    id: 'lunch-dalia-sabzi-curd',
    name: 'Dalia Bowl with Sabzi and Curd',
    slots: 'lunch',
    calories: 390,
    protein: 14,
    carbs: 55,
    fat: 10,
    portionItems: [{ label: 'dalia', quantity: 1, unit: 'bowl' }, { label: 'sabzi', quantity: 1, unit: 'cup' }, { label: 'curd', quantity: 0.5, unit: 'cup' }],
    ingredients: ['dalia', 'curd', 'carrot', 'peas', 'capsicum'],
    primaryIngredients: ['dalia'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Steady-energy lunch using broken wheat and curd.',
    recipe: {
      cookTime: '22 min',
      steps: ['Cook dalia until fluffy.', 'Prepare a dry sabzi.', 'Serve with curd on the side.'],
      tips: 'Useful when you want rice-like comfort but more fiber.',
    },
  }),

  meal({
    id: 'dinner-paneer-tikka-salad',
    name: 'Paneer Tikka with Salad',
    slots: 'dinner',
    calories: 350,
    protein: 24,
    carbs: 10,
    fat: 22,
    portionItems: [{ label: 'paneer tikka', quantity: 150, unit: 'g' }, { label: 'salad', quantity: 1, unit: 'bowl' }],
    ingredients: ['paneer', 'curd', 'capsicum', 'onion', 'cucumber'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein', 'light-dinner'],
    goalTags: ['weight-loss', 'muscle-gain'],
    description: 'Lighter dinner centered around grilled paneer.',
    recipe: {
      cookTime: '20 min',
      steps: ['Marinate paneer.', 'Grill with vegetables.', 'Serve with salad and chutney.'],
      tips: 'Skip heavy gravy at dinner if leaning out.',
    },
  }),
  meal({
    id: 'dinner-tofu-stir-fry',
    name: 'Tofu Stir Fry with Vegetables',
    slots: 'dinner',
    calories: 280,
    protein: 20,
    carbs: 14,
    fat: 14,
    portionItems: [{ label: 'tofu stir fry', quantity: 1, unit: 'bowl' }],
    ingredients: ['tofu', 'capsicum', 'broccoli', 'onion', 'garlic'],
    primaryIngredients: ['tofu'],
    tags: ['vegan', 'high-protein', 'light-dinner'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Quick stir fry with tofu and vegetables.',
    recipe: {
      cookTime: '15 min',
      steps: ['Cube tofu.', 'Stir fry garlic and vegetables.', 'Add tofu and cook until lightly crisp.'],
      tips: 'Use minimal oil and a hot pan for better texture.',
    },
  }),
  meal({
    id: 'dinner-moong-dal-khichdi',
    name: 'Moong Dal Khichdi',
    slots: 'dinner',
    calories: 300,
    protein: 12,
    carbs: 46,
    fat: 7,
    portionItems: [{ label: 'khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['rice', 'moong dal', 'cumin', 'ghee'],
    primaryIngredients: ['rice', 'moong dal'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Comforting light dinner for easy digestion.',
    recipe: {
      cookTime: '20 min',
      steps: ['Cook rice and dal with extra water.', 'Season lightly with cumin.', 'Serve soft and warm.'],
      tips: 'Good option on low-appetite or late evenings.',
    },
  }),
  meal({
    id: 'dinner-palak-dal-roti',
    name: 'Palak Dal with Roti',
    slots: 'dinner',
    calories: 400,
    protein: 18,
    carbs: 45,
    fat: 11,
    portionItems: [{ label: 'palak dal', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['spinach', 'dal', 'atta', 'garlic'],
    primaryIngredients: ['spinach', 'dal', 'atta'],
    tags: ['vegetarian'],
    goalTags: ['weight-loss', 'maintenance', 'fitness'],
    description: 'Spinach-lentil dinner with rotis.',
    recipe: {
      cookTime: '25 min',
      steps: ['Cook dal.', 'Blend or chop spinach.', 'Combine and temper with garlic.'],
      tips: 'Drop to 1 roti for a lighter dinner.',
    },
  }),
  meal({
    id: 'dinner-egg-bhurji-roti',
    name: 'Egg Bhurji with Rotis',
    slots: 'dinner',
    calories: 380,
    protein: 22,
    carbs: 28,
    fat: 18,
    portionItems: [{ label: 'egg bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['eggs', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['eggs'],
    tags: ['egg', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance', 'fitness'],
    description: 'Simple egg dinner with controlled carbs.',
    recipe: {
      cookTime: '15 min',
      steps: ['Prepare masala base.', 'Scramble eggs into it.', 'Serve with fresh rotis.'],
      tips: 'Use 2 whole eggs plus 2 whites for a leaner high-protein dinner.',
    },
  }),
  meal({
    id: 'dinner-paneer-bhurji-roti',
    name: 'Paneer Bhurji with Rotis',
    slots: 'dinner',
    calories: 380,
    protein: 21,
    carbs: 26,
    fat: 19,
    portionItems: [{ label: 'paneer bhurji', quantity: 1, unit: 'bowl' }, { label: 'roti', quantity: 2, unit: 'piece' }],
    ingredients: ['paneer', 'onion', 'tomato', 'atta'],
    primaryIngredients: ['paneer'],
    tags: ['vegetarian', 'high-protein'],
    goalTags: ['muscle-gain', 'maintenance'],
    description: 'Reliable vegetarian dinner with good protein.',
    recipe: {
      cookTime: '18 min',
      steps: ['Crumble paneer.', 'Cook with masala.', 'Serve with rotis.'],
      tips: 'Works well with cucumber salad on the side.',
    },
  }),
  meal({
    id: 'dinner-dalia-khichdi',
    name: 'Dalia Khichdi',
    slots: 'dinner',
    calories: 280,
    protein: 9,
    carbs: 44,
    fat: 7,
    portionItems: [{ label: 'dalia khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['dalia', 'carrot', 'peas', 'onion'],
    primaryIngredients: ['dalia'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Broken wheat one-pot dinner with vegetables.',
    recipe: {
      cookTime: '22 min',
      steps: ['Roast dalia lightly.', 'Cook with vegetables and spices.', 'Serve soft and hot.'],
      tips: 'Useful when you want a cereal-based dinner lighter than roti-sabzi.',
    },
  }),
  meal({
    id: 'dinner-oats-khichdi',
    name: 'Oats Khichdi with Vegetables',
    slots: 'dinner',
    calories: 260,
    protein: 10,
    carbs: 38,
    fat: 7,
    portionItems: [{ label: 'oats khichdi', quantity: 1, unit: 'bowl' }],
    ingredients: ['oats', 'moong dal', 'peas', 'carrot'],
    primaryIngredients: ['oats'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'fitness'],
    description: 'Quick oats-based savory bowl.',
    recipe: {
      cookTime: '15 min',
      steps: ['Toast oats lightly.', 'Cook with vegetables and moong dal.', 'Serve warm.'],
      tips: 'Helps on nights when digestion needs to stay easy.',
    },
  }),
  meal({
    id: 'dinner-kadhi-roti',
    name: 'Kadhi with 1 Roti',
    slots: 'dinner',
    calories: 280,
    protein: 10,
    carbs: 30,
    fat: 11,
    portionItems: [{ label: 'kadhi', quantity: 1, unit: 'cup' }, { label: 'roti', quantity: 1, unit: 'piece' }],
    ingredients: ['curd', 'besan', 'atta'],
    primaryIngredients: ['curd', 'besan'],
    tags: ['vegetarian', 'light-dinner'],
    goalTags: ['weight-loss', 'maintenance'],
    description: 'Simple lighter dinner with one roti.',
    recipe: {
      cookTime: '20 min',
      steps: ['Whisk curd and besan.', 'Cook slowly until smooth.', 'Serve with one roti.'],
      tips: 'Avoid a very oily tempering if cutting calories.',
    },
  }),
];

export const ingredientAliasMap = {
  atta: ['atta', 'wheat flour', 'whole wheat', 'multigrain toast', 'toast', 'bread'],
  rice: ['rice', 'brown rice', 'steamed rice', 'lemon rice'],
  urad_dal: ['urad dal'],
  toor_dal: ['toor dal', 'arhar dal'],
  moong_dal: ['moong dal', 'green moong'],
  dal: ['dal', 'masoor dal', 'chana dal', 'toor dal', 'moong dal', 'urad dal', 'kaali daal', 'kali dal'],
  rajma: ['rajma'],
  chole: ['chole', 'chana', 'chickpeas', 'chickpea'],
  eggs: ['egg', 'eggs'],
  paneer: ['paneer'],
  tofu: ['tofu'],
  curd: ['curd', 'yogurt', 'dahi', 'greek yogurt'],
  whey_protein: ['whey protein', 'whey'],
  poha: ['poha'],
  besan: ['besan'],
  oats: ['oats'],
  dalia: ['dalia', 'broken wheat'],
  quinoa: ['quinoa'],
  sprouts: ['sprouts', 'sprouted moong', 'moong sprouts'],
  makhana: ['makhana', 'fox nuts', 'fox nut'],
  milk: ['milk'],
  spinach: ['spinach', 'palak'],
  onion: ['onion'],
  tomato: ['tomato', 'tamatar'],
  capsicum: ['capsicum'],
  peas: ['peas', 'matar'],
  carrot: ['carrot'],
  cucumber: ['cucumber', 'kheera'],
  banana: ['banana'],
  apple: ['apple'],
  orange: ['orange'],
  almonds: ['almond', 'almonds'],
  walnuts: ['walnut', 'walnuts'],
  flaxseeds: ['flaxseeds', 'flax seeds'],
  chia_seeds: ['chia seeds', 'chia'],
};

